config/routes.rb
    registrations: 'users/registrations'
  }
  devise_scope :user do
    put "assume_user", to: "users/sessions#assume", as: "assume_user"
    delete "release_user", to: "users/sessions#release", as: "release_user"
    get "clear_session", to: "users/sessions#clear", as: "clear_session"
  end  
  devise_for :system_users

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  authenticate :system_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: "users#show"

  get 'help', to: 'help#index' # '/help', controller:  'Help', action:  'index'
  get 'system', to: 'system#index'
  get 'admin', to: 'admin#index'
  get 'survey', to: 'survey#index'
  get 'home', to: 'users#show'

#   system '/system', controller:  'System', action:  'index'
#   survey '/survey/', controller:  'Survey', action:  'index'

#   logout   '/logout',   controller:  'sessions', action:  'destroy'
#   login    '/login',    controller:  'sessions', action:  'new'
#   home     '/home',     controller:  'users',    action:  'show'
#   home     '/admin',    controller:  'Admin::Chambers',    action:  'show'

#   remember_password '/remember_password',
#     controller:  'users',
#     action:  'remember_password'
#
#   reset_password '/reset_password/:password_reset_code',
#     controller:  'users',
#     action:  'reset_password',
#     password_reset_code:  nil
#
#   activate '/activate/:activation_code',
#     controller:  'users',
#     action:  'activate',
#     activation_code:  nil
#
#   legacy_activate '/start/initUser.cgi',
#     controller:  'users',
#     action:  'activate',
#     activation_code:  nil


#   root controller:  :sessions, action:  :new

  resources :users do
    collection do
      post :request_password_reset
      post :confirm_payment
      patch :update_password
      get :edit_password
    end
  end

  namespace :payments do
    get  :elavon
    post :elavon_checkout
  end

  # resource :session, member:  {
  #   assume:  :put, release:  :put
  # }

  resources :members do
    get :details, on: :member
  end
  resources :administrators
  resources :instructors
  resources :executives

  resources :discussions do
    resources :comments
  end
  resource :comments


  resources :legislation do #, singular:  :legislation_instance,
    get :search, on: :collection
    put :add_cosponsor, on: :member
    put :remove_cosponsor, on: :member
  end
  resources :committees do
    get :membership_requests, on: :collection
    put :update_membership_requests, on: :collection
    member do
      post :generate_special_rule
      post :propose_special_rule
      get  :draft_special_rule
      get  :manage_special_rules
      get  :manage_discussions
      get  :manage_referrals
      get  :manage_votes
      get  :manage_info
      get  :manage
    end
  end

  resources :sections do
    member do
      get :manage_discussions
      get :manage_referrals
      get :manage_info
      get :manage
    end
  end
  resources :caucuses do
    member do
      patch :join
      patch :leave
      get :manage_discussions
      get :manage_referrals
      get :manage_info
      get :manage_votes
      get :manage
    end
  end
  resources :parties do
    member do
      patch :join
      patch :leave
      get :manage_discussions
      get :manage_referrals
      get :manage_info
      get :manage_votes
      get :manage
    end
  end
  resources :floors do
    member do
      get  :manage_info
      get  :manage_referrals
      get  :manage_calendars
      get  :manage_votes
      get  :manage_proceedings
      get  :new_proceeding
      get  :previous_proceeding
      post :create_previous_proceeding
      post :propose_proceeding
      post :generate_proceeding
      get  :manage
    end
  end
  resources :legislative_types
  resources :letters do
    get :reply, on: :member
    get :reply_all, on: :member
    get :sent, on: :collection
  end

  resources :leadership_nominations

  resources :survey do
    put :create, on: :member
  end

  resources :votes do
    member do
      patch  :cancel
      get    :edit_previous
      post   :create_previous
      patch  :update_previous
    end
  end
  resources :ballots
  resources :motions do
    member do
      post :join_filibuster
      post :leave_filibuster
    end
  end

  resources :calendars do
    collection do
      post :add_items
      get  :holds
      post :place_hold
      post :remove_hold
    end
  end
  resources :surveys
  resources :tutorials
  resources :instructions

  resources :chambers do
    member do
      get :visit
      get :manage
      get :edit_committee_referrals
      patch :update_committee_referrals
      patch :undo_committee_referral
      get :edit_committee_assignments
      patch :update_committee_assignments
      get :edit_committee_primary_leaders
      patch :update_committee_primary_leaders
    end
    resources :legislation #, singular:  :legislation_instance
    resources :committees
    resources :caucuses
    resources :parties
    resources :legislative_types
    resources :letters, action:  'new'
  end

  resources :referrals do
    resources :amendments
    resources :reports
    resources :votes do
      collection do
        post :create_previous
        get  :previous
        get  :amendment_options
        get  :amendment_text
        get  :report_text
        get  :final_passage_options
        get  :final_passage_text
        get  :cloture_text
      end
    end
  end

  resources :reports do
    put :publish, on: :member
  end
  resources :amendments

  resources :courses do
    resources :chambers
  end

  resources :groups do
    get :csv, on: :member
    resources :calendars
    resources :votes
  end


  namespace :system do

    resources :system_users
    resources :users do
      collection do
        get :find
      end
      member do
        put :send_confirmation
        patch :update_password
        put :assume
      end
      resources :payments do
        put :refund, on: :member
      end
    end
    resources :courses do
      get :archives, on:  :collection
      resources :chambers do
        member do
          put :reinitialize
          get :export_content
        end
      end
    end

    # system authentication routes

#     system.logout   '/logout',   controller:  'sessions',     action:  'destroy'
#     system.login    '/login',    controller:  'sessions',     action:  'new'
#     system.register '/register', controller:  'system_users', action:  'create'
#     system.signup   '/signup',   controller:  'system_users', action:  'new'
#     system.reset_password '/reset_password/:password_reset_code',
#       controller:  'system_users',
#       action:  'reset_password',
#       password_reset_code:  nil
#     system.activate '/activate/:activation_code',
#       controller:  'system_users',
#       action:  'activate',
#       activation_code:  nil
#     system.resource :session, member:  {
#       assume:  :put
#     }

  end

  namespace :admin do

    resources :chambers do
      member do
        get :edit_constituencies
        put :update_constituencies
        put :init_constituencies
        get :edit_survey_questions
        put :update_survey_questions
        put :init_survey_questions
        get :edit_committees
        put :update_committeees
        put :init_committees
        get :edit_legislative_types
        put :update_legislative_types
        put :init_legislative_types
        get :edit_chamber_roles
        put :update_chamber_roles
        get :edit_contents
        put :update_contents
        get :new_referrals
        put :create_referrals
      end
    end

    resources :groups do
      get :edit_leadership, on: :collection
      put :update_leadership, on: :collection
    end

    resources :calendars do
      put :update_positions, on: :member
    end
    resources :votes
    resources :referrals
    resources :legislation do
      resources :referrals
    end
    resources :legislative_types
    resources :constituencies do
      post :mass_delete, on: :collection
    end
    resources :survey_questions

    resources :users do
      member do
        get :edit_password
        put :update_password
        put :send_password_reset
      end
    end
    resources :members do
      collection do
        get  :mass_new
        post :mass_create
        post :mass_delete
      end
    end
    resources :administrators
    resources :executives
    resources :instructors

    resources :committees do
      member do
        put :update_leadership
        put :add_members
        put :remove_members
        get :download_stats
      end
      post :mass_delete, on: :collection
    end
    resources :sections do
      member do
        put :update_leadership
        put :add_members
        put :remove_members
        get :download_stats
      end
      post :mass_delete, on: :collection
    end
    resources :parties do
      member do
        put :update_leadership
        put :add_members
        put :remove_members
        get :download_stats
      end
      post :mass_delete, on: :collection
    end
    resources :caucuses do
      member do
        put :update_leadership
        put :add_members
        put :remove_members
        get :download_stats
      end
      post :mass_delete, on: :collection
    end
    resources :floors do
      get :download_stats, on: :member
    end

    resources :groups do
      collection do
        get :committees
        get :parties
        get :caucuses
      end
    end
    resources :contents do
      get  :export, on: :collection
      post :init, on: :collection
    end
    resources :settings do
      post :mass_update, on: :collection
    end

    resources :instructions do
      post :reorder, on: :collection
    end
    resources :tutorials do
      post :reorder, on: :collection
    end
  end

  resources :examples

app/models/letter.rb
class Letter < ActiveRecord::Base

  belongs_to :chamber_role
  belongs_to :chamber

  has_many :letter_user_recipients
  has_many :letter_group_recipients
  has_many :letter_meta_group_recipients

  before_validation :set_chamber, on: :create

  scope :unnotified, -> {where(notified:false)}
  scope :notified, -> {where(notified:true)}

  def set_chamber
    self.chamber = chamber_role.chamber
  end

  def sender_title
    chamber_role.title
  end

  def recipient_list

    letter_user_recipients.includes(:chamber_role).where( letter_group_recipient_id: nil, letter_meta_group_recipient_id: nil, blind: false ).collect do |recipient|
      recipient.chamber_role&.title
    end + letter_group_recipients.includes(:group).collect do |recipient|
      recipient.group&.title
    end + letter_meta_group_recipients.all.collect do |recipient|
      recipient.name&.titleize
    end

  end

  def recipient_string
    recipient_list.join(', ')
  end

  def to_html_tr
  end

end

app/models/user.rb
require 'digest/sha1'
require 'digest/md5'
require 'net/smtp'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable, :validatable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, authentication_keys: [:email,:course_id]

  validates_presence_of :email
  validates_format_of :email, with: /\A[^@\s]+@[^@\s]+\z/, allow_blank: true, if: :email_changed?
  validates_uniqueness_of :email, case_sensitive: false, allow_blank: true, if: :email_changed?, scope: :course_id

  belongs_to :course
  belongs_to :last_chamber, class_name: 'Chamber', optional: true

  has_many :chamber_roles, dependent: :destroy
  has_many :actions, dependent: :destroy
  has_many :payments

  after_create :generate_payment_token

  def self.make_activation_code( seed = nil )
    # make activation code by MD5ing a provided seed
    activation_code = Digest::MD5.hexdigest( seed )

    # if the code is already in use, generate a new code using the old code as a seed, otherwise pass the finished code back
    User.find_by_activation_code(activation_code) ? make_activation_code( activation_code ) : activation_code
  end

  def has_license?
    if course.payment_prepaid?
      true
    else
      payments.paid.any?
    end
  end

  def views_by_week

    views = []

    start_at = actions.get.first.created_at
    end_at = 1.week.since(start_at)

    while ( start_at < Time.now )

      views.push(
        {
          :week => "#{start_at.to_s(:short)} - #{end_at.to_s(:short)}",
          :count => actions.count(:all, :conditions => ['created_at > ? AND created_at <= ?',start_at,end_at])
        }
      )

      start_at = end_at
      end_at = 1.week.since(start_at)

    end

    views
  end

  def posts_by_week
    views = []

    start_at = actions.post.first.created_at
    end_at = 1.week.since(start_at)

    while ( start_at < Time.now )

      views.push(
        {
          :week => "#{start_at.to_s(:short)} - #{end_at.to_s(:short)}",
          :count => actions.count(:all, :conditions => ['created_at > ? AND created_at <= ?',start_at,end_at])
        }
      )

      start_at = end_at
      end_at = 1.week.since(start_at)

    end

    views
  end


  def chamber_role( chamber )
    ChamberRole.find_by_user_id_and_chamber_id( self.id, chamber.id )
  end

  def email=(value)
    write_attribute :email, (value ? value.downcase : nil)
  end

  def name
    "#{first_name} #{last_name}"
  end

  def title
    name
  end

  def send_activation_code

    message = <<END_OF_MESSAGE
From: LegSim <no-reply@legsim.org>
To: #{email}
Subject: LegSim Activation

Your account is ready, all you need to do is activate it by following this link:
#{activation_url}

After you have activated your account and set up your profile, we invite you to look around a little. Under 'members' you will find the ability to edit your profile, change your password, and take a look at other student's profiles. Under 'tutorials' you'll find extensive information about the legislative process and the roles of different kinds of legislators. Under 'instruction' you find examples of bills and committee hearings. Good luck!
END_OF_MESSAGE

    Net::SMTP.start('localhost') do |smtp|
    smtp.send_message message, 'no-reply@legsim.org', email
    end
  end

  def send_password_reset_code

    make_password_reset_code

    message = <<END_OF_MESSAGE
From: LegSim <no-reply@legsim.org>
To: #{email}
Subject: LegSim Password Reset

A request has been made to reset your password. To do so, follow this link and provide a new password:
#{password_reset_url}
END_OF_MESSAGE

    Net::SMTP.start('localhost') do |smtp|
      smtp.send_message message, 'no-reply@legsim.org', email
    end
  end

  def generate_payment_token
    if course.payment_uw_cforc?
      self.payment_token = id.to_s.crypt('7db8f9a8c1160469')
      save
    end
  end

  def generate_random_password
    (0...8).collect { |n| ('a'..'z').to_a[rand(26)] }.join()
  end

  def activation_url
    "http://#{APP_CONFIG['domain']}/activate/#{activation_code}"
  end

  def password_reset_url
    "http://#{APP_CONFIG['domain']}/reset_password/#{password_reset_code}"
  end

  protected

    def make_password_reset_code
      self.password_reset_code = self.class.make_token
      save
    end

    def make_activation_code

      self.deleted_at = nil
      self.activation_code = self.class.make_activation_code("#{email}#{course_id}")
      if course.payment_prepaid?
        send_activation_code
      elsif course.payment_foliodirect? or course.payment_uw_cforc?
        send_activation_code unless chamber_roles.first.is_member?
      end
    end
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/letters/_mailbox.html.erb
  <div id="mailbox" class="expander expanded">
    <div class="bar clearfix">
      <h2 class="title">Dear Colleague <!--<span class="parenthesis">(7 unread)</span>--></h2>
      <div style='float:right'>
        <a href="/letters/new">Compose</a> |
        <a href="/letters/sent">Sent</a>
      </div>
    </div><!--bar-->
    <div class="expander-contents">
    <table cellspacing="0">
      <tbody id="mailbox_body">
      </tbody>
      <tfoot>
          <tr>
            <td colspan="4" id="mailbox_footer" style='text-align: center'></td>
          </tr>
      </tfoot>
    </table>
    </div><!--expander-contents-->
  </div><!--mailbox-->

<script type="text/javascript">
  mailbox_offset = 0
  mailbox_limit = 10

  function get_mailbox(offset,limit){
    $.get('/letters.json?offset=' + offset + '&limit=' + limit,{},function(data){
      $("#mailbox_body").html( data.mailbox_body );
      $("#mailbox_footer").html( data.mailbox_footer );

      $("a[href='#oldest']").click(function(){
        if (data.offset+mailbox_limit < data.total)
          get_mailbox(data.total-mailbox_limit,mailbox_limit)
        return false;
      });

      $("a[href='#older']").click(function(){
        if (data.offset+mailbox_limit < data.total)
          get_mailbox(data.offset+mailbox_limit,mailbox_limit)
        return false;
      });

      $("a[href='#newer']").click(function(){
        if (data.offset-mailbox_limit >= 0)
          get_mailbox(data.offset-mailbox_limit,mailbox_limit)
        return false;
      });

      $("a[href='#newest']").click(function(){
        if (data.offset >= 0)
          get_mailbox(0,mailbox_limit)
        return false;
      });

    },'json');
  }

  $().ready(function() { get_mailbox(mailbox_offset,mailbox_limit) });
</script>

app/views/letters/index.html.erb
<h1>Letter</h1>

<p>
  <% @letters.each do |letter| %>
    <%= link_to "show", letter_path( letter ) %> :
    <%= letter.subject %>
    <br />
  <% end %>
</p>

<p><%= link_to "Create New Letter", new_letter_path %><br /></p>

app/views/letters/new.html.erb
<script type="text/javascript">

  $().ready(function() {
    $("#new_letter").submit(function() {

      var errors = [];

      if ( !$("#letter_subject").val() ) errors.push( 'No subject provided' );
      if ( !$("#letter_message").val() ) errors.push( 'No message provided' );
      if ( !$("input:checked").length ) errors.push( 'No recipients selected' );

      if ( errors.length ){
        $("#validation-box").show();
        $("#form-errors").html("<li>" + errors.join('</li><li>') + "</li>");
        return false;
      } else {
        $("#validation-box").hide();
        return true;
      }

    });
  });

</script>
<!-- <div class="left-column">
  <div class="left-content">
    Figure it out!
  </div>
</div>

<div class="right-column">
  <div class="the-content">
    This is getting ridiculous
  </div>
</div> -->

<%= form_for @letter do |f| %>

  <div id="overview" class="left-column" style="float: left;">
    <div class="left-content">
      <%= content('draft-dear-colleague') %>

      <h2>Address the Message</h2>

      <div id="tab-container" class="tab-container">
        <ul class="etabs" style="display:inline-block">
          <li class="tab" style='width: 100%'><a href="#tab-members">Members</a></li>
          <li class="tab" style='width: 100%'><a href="#tab-committees">Committees</a></li>
          <li class="tab" style='width: 100%'><a href="#tab-organizations">Organizations</a></li>
          <li class="tab" style='width: 100%'><a href="#tab-special">Special</a></li>
        </ul>
        
        <br/>
        <br/>
        <hr/>
        <div class="panel" id="tab-members">
          <ul class="checkbox"><% @chamber.members.includes( :constituency ).each do | member | %>
            <li><%= check_box_tag "chamber_role_ids[]", member.id, @reply_to[:chamber_role_ids][member.id] %> <%= member.title %></li>
          <% end %></ul>
        </div>

        <div class="panel" id="tab-committees">
          <ul class="checkbox"><% @chamber.committees.each do | committee | %>
            <li><%= check_box_tag "group_ids[]", committee.id, @reply_to[:group_ids][committee.id] %> <%= committee.title %></li>
          <% end %></ul>
        </div>

        <div class="panel" id="tab-organizations">
          <h2>Parties</h2>
          <ul class="checkbox"><% @chamber.parties.each do | party | %>
            <li><%= check_box_tag "group_ids[]", party.id, @reply_to[:group_ids][party.id] %> <%= party.title %></li>
          <% end %></ul>

          <h2>Caucuses</h2>
          <ul class="checkbox"><% @chamber.caucuses.each do | caucus | %>
            <li><%= check_box_tag "group_ids[]", caucus.id, @reply_to[:group_ids][caucus.id] %> <%= caucus.title %></li>
          <% end %></ul>

          <% unless @chamber.sections.empty? %>
            <h2>Sections</h2>
            <ul class="checkbox"><% @chamber.sections.each do | section | %>
              <li><%= check_box_tag "group_ids[]", section.id, @reply_to[:group_ids][section.id] %> <%= section.title %></li>
            <% end %></ul>
          <% end %>
        </div>

        <div class="panel" id="tab-special">

          <ul class="checkbox">
            <li><%= check_box_tag "group_ids[]", @chamber.floor.id, @reply_to[:group_ids][@chamber.floor.id] %> <%= @chamber.floor.name %></li>
          </ul>

          <h2>Leadership</h2>
          <ul class="checkbox">
            <li><%= check_box_tag "meta_group_ids[]", 'chamber_leader', @reply_to[:meta_group_ids]['chamber_leader'] %> <%= @current_chamber.setting('chamber_leader_title') %></li>
            <li><%= check_box_tag "meta_group_ids[]", 'committee_leaders', @reply_to[:meta_group_ids]['committee_leaders'] %> Committee Leaders</li>
            <li><%= check_box_tag "meta_group_ids[]", 'party_leaders', @reply_to[:meta_group_ids]['party_leaders'] %> Party Leaders</li>
            <li><%= check_box_tag "meta_group_ids[]", 'caucus_leaders', @reply_to[:meta_group_ids]['caucus_leaders'] %> Caucus Leaders</li>
          </ul>

          <% if @chamber.setting('has_executive') and !@chamber.executives.empty? %>
            <h2>Executive</h2>
            <ul class="checkbox">
              <% @chamber.executives.each do |executive| %>
                <li><%= check_box_tag "chamber_role_ids[]", executive.id, @reply_to[:chamber_role_ids][executive.id] %> <%= executive.title %></li>
              <% end %>
            </ul>
          <% end %>

          <% if !@chamber.instructors.empty? %>
            <h2>Instructors</h2>
            <ul class="checkbox">
              <% @chamber.instructors.each do |instructor| %>
                <li><%= check_box_tag "chamber_role_ids[]", instructor.id, @reply_to[:chamber_role_ids][instructor.id] %> <%= instructor.title %></li>
              <% end %>
            </ul>
          <% end %>

          <h2>Management</h2>
          <ul class="checkbox">
            <li><%= check_box_tag "meta_group_ids[]", 'administrators', @reply_to[:meta_group_ids]['administrators'] %> Administrators</li>
            <li><%= check_box_tag "meta_group_ids[]", 'instructors', @reply_to[:meta_group_ids]['instructors'] %> Instructors</li>
          </ul>


          <!--
            <h2>Sections</h2>
            <ul><% @chamber.sections.each do | party | %>
              <li><%= check_box_tag "group_ids[]", party.id, false %> <%= party.title %></li>
            <% end %></ul>
          -->
        </div>
      </div>
    </div>
  </div>

  <div id="details" class="right-column" style="float: left;">
    <div class="the-content">
      <div class="alert-box" style="display:none" id="validation-box">
        <h2 class="error">Error</h2>
        <ul id="form-errors"></ul>
      </div>

      <h2>Compose the Message</h2>
      <div class="field">
        <%= form_field :tip => "Don't mess with this" do %>
          <%= f.label :subject%> <%= f.text_field :subject %>
        <% end %>
      </div>

      <div class="field text-field">
        <%= form_field do %>
          <%= f.label :message%> <%= f.text_area :message %>
        <% end %>
      </div>

      <%= f.hidden_field :chamber_role_id %>

      <div class="field field-submit">
        <%= f.submit 'Send Letter', :class => "btn blue-btn" %>
      </div>
    </div>
  </div>
<% end %>

app/views/letters/sent.html.erb
<div class='left-column'>
  <div class='left-content'>
    <p>Here is a record of all the dear colleague letters that you have sent.</p>
  </div>
</div>
<div class='right-column'>
  <div class="the-content">
    <h1>Sent Letters</h1>
    <br/>
      <ul>
        <% @letters.reverse.each do |letter| %>
          <div class="expander expanded">
            <div id="mail-header" style="border: 0px; padding: 0px;">

              <h2><%= link_to letter.subject, letter_path( letter ) %></h2>
              <table cellspacing="0">
                <tr>
                  <td style='float:right;'>Sent</td>
                  <td><%= letter.created_at.to_s(:long_with_time) %></td>
                </tr>
                <tr>
                  <td style='float:right;'>To</td>
                  <td><%= letter.recipient_list.join(', ') %></td>
                </tr>
              </table>
            </div>
          </div>
          <br/>
        <% end %>
      </ul>
    
    <p class='field field-submit'>
      <%= link_to "Create New Letter", new_letter_path, :class => 'btn blue-btn' %>
      <br />
    </p>
  </div>
</div>

app/views/letters/show.html.erb
<div id="overview" class="left-column">
  <div class="left-content">
  <div id="mail-actions" class="clearfix">
    <%= link_button_to "Reply", reply_letter_path( @letter ), :class => 'btn blue-btn' %>
    <br/>
    <%= link_button_to "Reply All", reply_all_letter_path( @letter ), :class => 'btn blue-btn' %>
<!--     <div class="button"><div class="left"><div class="right"><a href="">Reply</a></div></div></div>
     <div class="button"><div class="left"><div class="right"><a href="">Reply All</a></div></div></div>-->

<!--     <div class="button"><div class="left"><div class="right"><a href="">Forward</a></div></div></div>
     <div class="button"><div class="left"><div class="right"><a href="">Delete</a></div></div></div>-->
  </div><!--mail-actions-->

  <h2><%= link_to_user( @letter.chamber_role ) %></h2>
  <table cellspacing="0">
  <tr>
    <th style='padding: 15px 0;'>Sent<td></td>
    <td><%= @letter.created_at.to_s(:long) %></td>
  </tr>
  <tr>
    <th>To</th><td></td>
    <td><%= @letter.recipient_list.join(', ') %></td>
  </tr>
  </table>
  </div>
</div><!--mail-header-->

<div id="details" class="right-column">
  <div class="the-content">
    <pre style="white-space: pre-wrap;font-size:18px;">
      <%= @letter.message%>

    </pre>
  </div>
</div><!--mail-message-->


<!--<div class="wide-form">
  <div id="overview">

    <h2>Delivery Information</h2>

    <h3>Sent By</h3>
    <p><%= @letter.chamber_role.title %></p>

    <h3>Date</h3>
    <p><%= @letter.created_at.strftime("%m/%d/%Y %H:%M %p") %></p>

    <h3>Recipient(s)</h3>
      <ul>
        <% @letter.recipient_list.each do |recipient| %>
          <li><%= recipient %></li>
        <% end %>
      </ul>

  </div>

  <div id="details">

    <h2>Subject</h2>

    <p><%= @letter.subject %></p>

    <h2>Message</h2>

    <pre class="letter"><%= @letter.message %></pre>

  </div>
</div>-->