config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    put "assume_user", to: "users/sessions#assume", as: "assume_user"
    delete "release_user", to: "users/sessions#release", as: "release_user"
    get "clear_session", to: "users/sessions#clear", as: "clear_session"
  end  
  devise_for :system_users

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  authenticate :system_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: "users#show"

  get 'help', to: 'help#index' # '/help', controller:  'Help', action:  'index'
  get 'system', to: 'system#index'
  get 'admin', to: 'admin#index'
  get 'survey', to: 'survey#index'
  get 'home', to: 'users#show'

#   system '/system', controller:  'System', action:  'index'
#   survey '/survey/', controller:  'Survey', action:  'index'

#   logout   '/logout',   controller:  'sessions', action:  'destroy'
#   login    '/login',    controller:  'sessions', action:  'new'
#   home     '/home',     controller:  'users',    action:  'show'
#   home     '/admin',    controller:  'Admin::Chambers',    action:  'show'

#   remember_password '/remember_password',
#     controller:  'users',
#     action:  'remember_password'
#
#   reset_password '/reset_password/:password_reset_code',
#     controller:  'users',
#     action:  'reset_password',
#     password_reset_code:  nil
#
#   activate '/activate/:activation_code',
#     controller:  'users',
#     action:  'activate',
#     activation_code:  nil
#
#   legacy_activate '/start/initUser.cgi',
#     controller:  'users',
#     action:  'activate',
#     activation_code:  nil


#   root controller:  :sessions, action:  :new

  resources :users do
    collection do
      post :request_password_reset
      post :confirm_payment
      patch :update_password
      get :edit_password
    end
  end

  namespace :payments do
    get  :elavon
    post :elavon_checkout
  end

  # resource :session, member:  {
  #   assume:  :put, release:  :put
  # }

  resources :members do
    get :details, on: :member
  end
  resources :administrators
  resources :instructors
  resources :executives

  resources :discussions do
    resources :comments
  end
  resource :comments


  resources :legislation do #, singular:  :legislation_instance,
    get :search, on: :collection
    put :add_cosponsor, on: :member
    put :remove_cosponsor, on: :member
  end
  resources :committees do
    get :membership_requests, on: :collection
    put :update_membership_requests, on: :collection
    member do
      post :generate_special_rule
      post :propose_special_rule
      get  :draft_special_rule
      get  :manage_special_rules
      get  :manage_discussions
      get  :manage_referrals
      get  :manage_votes
      get  :manage_info
      get  :manage
    end
  end

  resources :sections do
    member do
      get :manage_discussions
      get :manage_referrals
      get :manage_info
      get :manage
    end
  end
  resources :caucuses do
    member do
      patch :join
      patch :leave
      get :manage_discussions
      get :manage_referrals
      get :manage_info
      get :manage_votes
      get :manage
    end
  end
  resources :parties do
    member do
      patch :join
      patch :leave
      get :manage_discussions
      get :manage_referrals
      get :manage_info
      get :manage_votes
      get :manage
    end
  end
  resources :floors do
    member do
      get  :manage_info
      get  :manage_referrals
      get  :manage_calendars
      get  :manage_votes
      get  :manage_proceedings
      get  :new_proceeding
      get  :previous_proceeding
      post :create_previous_proceeding
      post :propose_proceeding
      post :generate_proceeding
      get  :manage
    end
  end
  resources :legislative_types
  resources :letters do
    get :reply, on: :member
    get :reply_all, on: :member
    get :sent, on: :collection
  end

  resources :leadership_nominations

  resources :survey do
    put :create, on: :member
  end

  resources :votes do
    member do
      patch  :cancel
      get    :edit_previous
      post   :create_previous
      patch  :update_previous
    end
  end
  resources :ballots
  resources :motions do
    member do
      post :join_filibuster
      post :leave_filibuster
    end
  end

  resources :calendars do
    collection do
      post :add_items
      get  :holds
      post :place_hold
      post :remove_hold
    end
  end
  resources :surveys
  resources :tutorials
  resources :instructions

  resources :chambers do
    member do
      get :visit
      get :manage
      get :edit_committee_referrals
      patch :update_committee_referrals
      patch :undo_committee_referral
      get :edit_committee_assignments
      patch :update_committee_assignments
      get :edit_committee_primary_leaders
      patch :update_committee_primary_leaders
    end
    resources :legislation #, singular:  :legislation_instance
    resources :committees
    resources :caucuses
    resources :parties
    resources :legislative_types
    resources :letters, action:  'new'
  end

  resources :referrals do
    resources :amendments
    resources :reports
    resources :votes do
      collection do
        post :create_previous
        get  :previous
        get  :amendment_options
        get  :amendment_text
        get  :report_text
        get  :final_passage_options
        get  :final_passage_text
        get  :cloture_text
      end
    end
  end

  resources :reports do
    put :publish, on: :member
  end
  resources :amendments

  resources :courses do
    resources :chambers
  end

  resources :groups do
    get :csv, on: :member
    resources :calendars
    resources :votes
  end


  namespace :system do

    resources :system_users
    resources :users do
      collection do
        get :find
      end
      member do
        put :send_confirmation
        patch :update_password
        put :assume
      end
      resources :payments do
        put :refund, on: :member
      end
    end
    resources :courses do
      get :archives, on:  :collection
      resources :chambers do
        member do
          put :reinitialize
          get :export_content
        end
      end
    end

    # system authentication routes

#     system.logout   '/logout',   controller:  'sessions',     action:  'destroy'
#     system.login    '/login',    controller:  'sessions',     action:  'new'
#     system.register '/register', controller:  'system_users', action:  'create'
#     system.signup   '/signup',   controller:  'system_users', action:  'new'
#     system.reset_password '/reset_password/:password_reset_code',
#       controller:  'system_users',
#       action:  'reset_password',
#       password_reset_code:  nil
#     system.activate '/activate/:activation_code',
#       controller:  'system_users',
#       action:  'activate',
#       activation_code:  nil
#     system.resource :session, member:  {
#       assume:  :put
#     }

  end

  namespace :admin do

    resources :chambers do
      member do
        get :edit_constituencies
        put :update_constituencies
        put :init_constituencies
        get :edit_survey_questions
        put :update_survey_questions
        put :init_survey_questions
        get :edit_committees
        put :update_committeees
        put :init_committees
        get :edit_legislative_types
        put :update_legislative_types
        put :init_legislative_types
        get :edit_chamber_roles
        put :update_chamber_roles
        get :edit_contents
        put :update_contents
        get :new_referrals
        put :create_referrals
      end
    end

    resources :groups do
      get :edit_leadership, on: :collection
      put :update_leadership, on: :collection
    end

    resources :calendars do
      put :update_positions, on: :member
    end
    resources :votes
    resources :referrals
    resources :legislation do
      resources :referrals
    end
    resources :legislative_types
    resources :constituencies do
      post :mass_delete, on: :collection
    end
    resources :survey_questions

    resources :users do
      member do
        get :edit_password
        put :update_password
        put :send_password_reset
      end
    end
    resources :members do
      collection do
        get  :mass_new
        post :mass_create
        post :mass_delete
      end
    end
    resources :administrators
    resources :executives
    resources :instructors

    resources :committees do
      member do
        put :update_leadership
        put :add_members
        put :remove_members
        get :download_stats
      end
      post :mass_delete, on: :collection
    end
    resources :sections do
      member do
        put :update_leadership
        put :add_members
        put :remove_members
        get :download_stats
      end
      post :mass_delete, on: :collection
    end
    resources :parties do
      member do
        put :update_leadership
        put :add_members
        put :remove_members
        get :download_stats
      end
      post :mass_delete, on: :collection
    end
    resources :caucuses do
      member do
        put :update_leadership
        put :add_members
        put :remove_members
        get :download_stats
      end
      post :mass_delete, on: :collection
    end
    resources :floors do
      get :download_stats, on: :member
    end

    resources :groups do
      collection do
        get :committees
        get :parties
        get :caucuses
      end
    end
    resources :contents do
      get  :export, on: :collection
      post :init, on: :collection
    end
    resources :settings do
      post :mass_update, on: :collection
    end

    resources :instructions do
      post :reorder, on: :collection
    end
    resources :tutorials do
      post :reorder, on: :collection
    end
  end

app/models/committee.rb
class Committee < Group

  def is_committee?
    true
  end

  def primary_group_leader_title
    chamber.setting('primary_committee_leader_title') || "Chair"
  end

end

app/controllers/admin/committees_controller.rb
class Admin::CommitteesController < AdminController

  def index
    @page_title = "Committee Management"
    @committees = current_chamber.committees
  end

  def show
    @committee = Committee.find( params[:id] )
    @page_title = "Manage Committee"
    @page_description = @committee.name
  end

  def new
    @page_title = "Create New Committee"
    @committee = current_chamber.committees.new
  end

  def create
    @committee = Committee.new( committee_params )
    if @committee.save
      flash_message("#{@committee.name} has been created")
      redirect_to( admin_committees_path )
    else
      render(:action => :new)
    end
  end

  def mass_delete
    if params[:group_ids].nil? or params[:group_ids].empty?
      flash_message("No committees were selected.",:error)
    else
      params[:group_ids].each do |id|
        Committee.destroy( id )
      end
      flash_message("#{ActionController::Base.helpers.pluralize(params[:group_ids].count, 'committee')} deleted.")
    end
    redirect_to( admin_committees_path )
  end

  def destroy
    committee = Committee.destroy( params[:id] )
    flash_message("#{committee.name} deleted.")
    redirect_to( admin_committees_path )
  end

  def edit
    @committee = Committee.find( params[:id] )
    @page_title = "Edit Committee"
    @page_description = @committee.name
  end

  def update
    @committee = Committee.find(params[:id])
    if @committee.update(committee_params)
      flash_message("Committee Information Updated")
      redirect_to( admin_committees_path )
    else
      @page_title = "Edit Committee"
      @page_description = @committee.name
      render(:action => :edit)
    end
  end

  def download_stats
    @committee = Committee.find(params[:id])
    send_data @committee.to_csv, :filename => @committee.name.parameterize + '.csv'
  end

  def update_leadership
    @committee = Committee.find(params[:id])
    @committee.assign_primary_group_leader( params[:primary_leader] )

    flash_message("Committee Leadership Updated")
    redirect_to( admin_committee_path( @committee ) )
  end

  def add_members
    @committee = Committee.find(params[:id])
    params[:chamber_role_ids].each do |chamber_role_id|
      @committee.add_member( chamber_role_id )
    end

    flash_message("Committee Members Added")
    redirect_to( admin_committee_path( @committee ) )
  end

  def remove_members
    @committee = Committee.find(params[:id])
    params[:chamber_role_ids].each do |chamber_role_id|
      @committee.remove_member( chamber_role_id )
    end

    flash_message("Committee Members Removed")
    redirect_to( admin_committee_path( @committee ) )
  end

  private

  def committee_params
    params.require(:committee).permit!
  end

end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController

  def manage
    @committee = Committee.find( params[:id] )
    @page_title = "Committee Management"
    @page_description = @committee.name
  end

  def propose_special_rule
    committee = Committee.find( params[:id] )

    legislation = Legislation.find( params[:legislation_ids].split(',') )

    legislative_references = legislation.collect {|leg| leg.reference }

    special_rule = Legislation.create!(
      :name             => "Special Rule for #{legislative_references.join(', ')}",
      :sponsor          => @current_chamber_role,
      :legislative_type => @current_chamber.legislative_type_for_special_rule,
      :status           => "draft",
      :submission_text  => LegislativeText.new(
        :primary_text => params[:draft_rule]
      )
    )

    legislation.each do |leg|
      special_rule.relate( :target => leg, :relation => "special_rule" )
    end

    referral = special_rule.referrals.create!(
      :group         => committee,
      :referrer      => @current_chamber_role,
      :referred_text => special_rule.submission_text,
      :status        => 'hearing',
      :priority      => 'rules'
    )

    referral.manage_discussion( :chamber_role => @current_chamber_role )

    flash_message("Special Rule has been proposed to the committee for consideration")
    redirect_to( referral_path(referral) )

  end

  def draft_special_rule
    @committee = Committee.find( params[:id] )
    @page_title = "Draft Special Rule"
    @page_description = @committee.name
  end

  def generate_special_rule
    @committee = Committee.find( params[:id] )

    @legislation = params[:legislation_ids].split(',').collect do |legislation_id|
      Legislation.find(legislation_id)
    end
  end

  def manage_discussions
    @committee = Committee.find( params[:id] )
    @page_title = "Committee Discussion Management"
    @page_description = @committee.name
  end

  def manage_referrals
    @committee = Committee.find( params[:id] )
    @page_title = "Committee Referral Management"
    @page_description = @committee.name
  end

  def manage_info
    @committee = Committee.find( params[:id] )
    @page_title = "Committee Information Management"
    @page_description = @committee.name
  end

  def membership_requests
    @page_title = "Committee Requests"
    @committees = current_chamber.committees
    @chamber_role = current_chamber_role
  end

  def update_membership_requests

    unless GroupMembershipRequest.find_by_group_id_and_chamber_role_id_and_rank(params[:rank_1],current_chamber_role.id,1)
      old_request = current_chamber_role.committee_request_by_rank(1)
      old_request.destroy if old_request
      GroupMembershipRequest.create!(
        :group_id => params[:rank_1],
        :chamber_role => current_chamber_role,
        :rank => 1
      ) unless params[:rank_1].blank?
    end

    unless GroupMembershipRequest.find_by_group_id_and_chamber_role_id_and_rank(params[:rank_2],current_chamber_role.id,1)
      old_request = current_chamber_role.committee_request_by_rank(2)
      old_request.destroy if old_request
      GroupMembershipRequest.create!(
        :group_id => params[:rank_2],
        :chamber_role => current_chamber_role,
        :rank => 2
      ) unless params[:rank_2].blank?
    end

    display_message("Your Membership Requests have been updated.")

    redirect_to( membership_requests_committees_path )
  end

  def manage_votes
    @committee = Committee.find( params[:id] )
    @page_title = "Committee Vote Management"
    @page_description = @committee.name
  end

  def index
    @committees = current_chamber.committees
    @page_title = 'Committee Directory'
  end

  def show
    @committee = Committee.find( params[:id] )
    @page_title = @committee.name
  end

  def new
    @committee = current_chamber.committees.new
  end

  def create
    @committee = Committee.new( committee_params )
    @committee.save ? redirect_to( @committee ) : render(:action => :new)
  end

  def edit
    @committee = Committee.find( params[:id] )
  end

  def update
    @committee = Committee.find(params[:id])
    if @committee.update( committee_params )
      flash_message("Committee Information Updated")
      redirect_to( manage_info_committee_path(@committee) )
    else
      @page_title = "Committee Information Management"
      @page_description = @committee.name
      render(:action => :manage_info)
    end
  end

  def destroy
    Committee.destroy( params[:id] )
    redirect_to( committees_path )
  end

  private
    
  def committee_params
    params.require(:committee).permit!
  end

end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/draft_special_rule.html.erb
<script type="text/javascript">
  $(document).ready(function(){

    $("#generate_draft_rule").click(function(){

      var post_url = '/committees/' + <%= @committee.id %> + '/generate_special_rule.js';
      var data = { legislation_ids: $("#legislation_ids").val().join(',') };

      $("#draft_rule").load(post_url,data);
      return false;

    });

  });
</script>

<%= form_for :committee, :url => propose_special_rule_committee_path( @committee ) do |f| %>

  <div id="overview" class="left-column">
    <div class="left-content">
      <h2>Special Rule Subject Matter</h2>
      <div class='field'><%= select_tag 'legislation_ids', options_for_select( @committee.chamber.legislation.under_consideration.collect{|l| [l.short_title,l.id]} ), :multiple => true, :style => "width: 100%;", :size => 15  %></div>
      <br /><br />
      <%= link_button_to "Generate Draft Rule", "#", :size => 'sixty', :id => 'generate_draft_rule', :class => 'btn blue-btn' %>
    </div>
  </div>

  <div id="details" class="right-column">
    <div class="the-content">
      <h2>Draft Special Rule</h2>

      <%= form_field do %>
        <%= text_area_tag :draft_rule, 
        '<p>Select a bill to your left, Enter the substance of a proposed Special Rule here. To send a Rule to the chamber, the committee must also vote to report it on a Motion to Report scheduled by the chair.</p>
          
         <p>Rules can propose just about anything in a Special Rule, but whatever is proposed is meaningless unless it is subsequently approved by a majority of the House. Open rules do little more than move a bill up the calendar. Closed rules can effectively cut off all amendments and debate.</p>

         <p><b>Open</b>. Allows any Member to offer an amendment under the five minute rule, provided that the amendment is germane.</p>

         <p><b>Modified Open</b>. Permits general debate and allows any Member to offer a germane amendment under the five minute rule subject only to an overall time limit on the amendment process, and/or a requirement that amendments be submitted in advance on LegSim.</p>

         <p><b>Structured (Modified Closed)</b>. The Rules Committee limits the amendments that may be offered to those designated in the special rule or Rules Committee report to accompany the special rule.</p> 

         <p><b>Closed</b>. Permits debate for a certain period of time-usually an hour-but permits no amendments to be offered.</p>', :class => 'tinymce field text-field', :style => 'width: 540px; height: 400px;' %>
      <% end %>
      <div class='field field-submit'>
        <%= f.submit "Propose for Committee Deliberation", :size => 'sixty', :class => 'btn blue-btn' %>
      </div>
    </div>
  </div>

<% end %>

app/views/committees/generate_special_rule.js.erb
<% @legislation.each do |legislation| %>
  <h3>Special Rule for the consideration of <%= legislation.reference %></h3>

  Initial version for consideration:
  <ul>
    <li><%= link_to "As Introduced in the #{legislation.chamber.name}", legislation_path( legislation ) %></li>
    <% legislation.referrals.committee.reported.each do |referral| %>
      <li><%= link_to "As Reported by #{referral.group.name}", report_path( referral.report ) %></li>
    <% end %>
  </ul>

  Time limit on debate:
  <ul>
    <li>Unlimited</li>
    <li>24 hours of online debate</li>
    <li>20 minutes of in class debate</li>
  </ul>

  Amendments to be considered:
  <ul>
    <li>Unlimited Amendments</li>
    <li>No Amendments</li>
    <% if legislation.status == 'calendar' %>
      <% legislation.referrals.floor.last.amendments.each do |amendment| %>
        <li><%= link_to amendment.title, amendment_path( amendment ) %> introduced by <%= link_to_user( amendment.sponsor ) %></li>
      <% end %>
    <% end %>
  </ul>

  Vote to be held:
  <ul>
    <li>Online over a period of 24 hours</li>
    <li>In class</li>
    <li>At the descrection of the <%= legislation.chamber.floor.primary_group_leader.title %></li>
  <ul>

<% end %>

app/views/committees/manage.html.erb
<% if @current_chamber_role.group_leader?( @committee ) %>
<div id="overview" class="left-column">
  <div class="left-content">
  <!-- <a href="http://youtu.be/H2U0dguktb0"><%= image_tag '/assets/img/video-camera.png', :alt => 'Committee Chair Video Tutorial', :title => 'Committee Chair Video Tutorial' %></a><br/> -->
  <%= content('manage-committee') %>
  </div>
</div>

<div id="details" class="right-column">

  <div class="the-content">
    <% if @committee.setting('can_draft_special_rule') %>
      <div class='field'>
        <%= link_to 'Draft Special Rule', draft_special_rule_committee_path(@committee) %>
      </div>
    <% end %>

    <div class='field'>
    <%= link_to 'Share information about the committee', manage_info_committee_path(@committee) %>
    </div>

  <div>
  <h2> Manage Referred bills </h2>
  </br>
  <p> A committee does not have to consider a bill. If it chooses to do so, the following steps are required
    in order to succesfully report (recommended) a bill to the full chamber. </p>
  </br>
  <p> Step 1: <%= link_to 'Open a hearing on the bill', manage_referrals_committee_path(@committee) %>
    (so that members can discuss and propose committee amendments) </p>

    <p> Step 2: <%= link_to 'Draft a committee report', manage_referrals_committee_path(@committee) %>
      that includes the committee’s assessment and recommended changes. </p>

      <p> Step 3:
          <% if @current_chamber.setting("has_#{@committee.type.underscore}_voting") %>
          <%= link_to 'Schedule votes on proposed committee amendments', manage_votes_committee_path(@committee) %>
         (or enter previous vote results). </p>
         <% end %>
      <!-- ASK - if statement below.  -->

      <p> Step 4:
        <% if @current_chamber.setting("has_#{@committee.type.underscore}_voting") %>
        <%= link_to 'Schedule a vote to adopt the drafted committee report ', manage_votes_committee_path(@committee) %>
       (or enter previous vote results). </p>
       <% end %>

     </br>
       <p> If the committee adopts the report, the bill is automatically referred to the chamber leader’s desk.
         However, when a bill is referred to more than one committee, all committees must first report it. </p>

      <p> The chair can also choose to <%= link_to 'open non-legislative hearings', manage_discussions_committee_path(@committee) %>
        that are not related to a particular bill. For example, sometimes committees
        develop legislation within committee and introduce the result as a new “clean” bill. </p>

  </div>


<!--
    <div class='field'>
      <%= link_to 'Manage Committee Information', manage_info_committee_path(@committee) %>
    </div>

    <div class='field'>
      <%= link_to 'Convene Hearings and Prepare Reports', manage_referrals_committee_path(@committee) %>
    </div>

    <div class='field'>
      <%= link_to 'Convene Non-Legislative Hearings', manage_discussions_committee_path(@committee) %>
    </div>

    <% if @current_chamber.setting("has_#{@committee.type.underscore}_voting") %>
      <div class='field'>
        <%= link_to 'Schedule Markup Votes and Motions to Report', manage_votes_committee_path(@committee) %>
      </div>
    <% end %> -->

    <div class='field field-submit'>
      <%= link_button_to "Return to Committee", committee_path( @committee ), :size => 'hundred', :class => 'btn blue-btn' %>
    </div>
  </div>
</div>
<% else %>
  You are not this committee's chair, you are not allowed to access this information.
<% end %>

app/views/committees/manage_referrals.html.erb
<% if @current_chamber_role.group_leader?( @committee ) %>
<div id="overview" class="left-column">
  <%= link_button_to "Return to Committee Management", manage_committee_path( @committee ), :size => 'hundred', :class => 'btn blue-btn' %>

  <div class="left-content">
    <%= content('manage-committee-referrals') %>
  </div>
  <div class='field field-submit'>
  </div>
</div>

<div id="details" class="right-column">
  <div class="the-content">
    <h2>Referrals</h2>

    <% if @committee.referrals.unreported.empty? %>
      <p>No bills have been referred to this committee.</p>
    <% else %>
      <table>
        <tr>
          <th style="width: 100%">Title</th>
          <th style="width: 140px" colspan="3">Actions</th>
        </tr>
        <% @committee.referrals.unreported.each do |referral| %>
          <%= render :partial => 'referrals/group_management_row', :locals => { :referral => referral } %>
        <% end %>
      </table>
    <% end %>

    <% unless @committee.referrals.reported.empty? %>

      <h2>Reports</h2>

      <table>
        <tr>
          <th style="width: 100%">Title</th>
          <th></th>
        </tr>
        <% @committee.referrals.reported.each do |referral| %>
          <tr>
            <td><%= referral.legislation.title %></td>
            <td>
              <%= link_button_to "View&nbsp;Report".html_safe, report_path( referral.report ), :size => 'ninty', :class => 'btn blue-btn' %>
            </td>
          <tr>
        <% end %>
      </table>

    <% end %>
  </div>
</div>
<% else %>
  You are not this committee's chair, you are not allowed to access this information.
<% end %>

app/views/committees/manage_votes.html.erb
<% if @current_chamber_role.group_leader?( @committee ) %>
<div id="overview" class="left-column">
  <%= link_button_to "Return to Committee Management", manage_committee_path( @committee ), :size => 'hundred', :class => 'btn blue-btn' %>

  <div class="left-content">

    <%= content('manage-committee-votes') %>
    <div class='field field-submit'>
    </div>
  </div>
</div>

<div id="details" class="right-column">
  <div class="the-content">
    <h2>Scheduled Votes</h2>

    <% if @committee.votes.pending.empty? %>
      <p>There are no pending votes.</p>
    <% else %>
      <table>
        <tr>
          <th>Title</th>
          <th style="width: 140px" colspan="2">Actions</th>
        </tr>
        <% @committee.votes.pending.each do |vote| %>
          <tr>
            <td>
              <%= vote.title %><br />
              &nbsp;&nbsp;&nbsp;<b>Start At:</b> <%= vote.start_at.to_s(:long_with_time) %><br />
              &nbsp;&nbsp;&nbsp;<b>Finish At:</b> <%= vote.finish_at.to_s(:long_with_time) %>
            </td>
            <td >
              <%= link_button_to "Edit&nbsp;Vote".html_safe, edit_vote_path(vote), :size => 'eighty', :class => 'btn blue-btn' %>
            </td>
            <td >
              <%= form_for vote, :url => {:action => 'cancel', :controller => :votes, :id => vote.id} do |f| %>
                <%= f.submit "Cancel", :size => 'hundred', :class => 'btn blue-btn' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>

    <h2>Legislation in Hearing</h2>

    <% if @committee.referrals.hearing.empty? %>
      <p>There is no legislation in hearing.</p>
    <% else %>
      <table>
        <tr>
          <th style="width: 100%">Title</th>
          <th style="width: 140px">Actions</th>
        </tr>
        <% @committee.referrals.hearing.each do |referral| %>
          <tr>
            <td><%= link_to_legislation( referral.legislation ) %></td>
            <td colspan="3">
              <%= link_button_to "Schedule&nbsp;Vote".html_safe, new_referral_vote_path(referral), :size => 'hundred', :class => 'btn blue-btn' %>
            </td>
            <td>
              <%= link_button_to "Enter&nbsp;Previous&nbsp;Vote".html_safe, previous_referral_votes_path(referral), :size => 'hundred', :class => 'btn blue-btn' %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>

      <h2>In Progress Votes</h2>

      <% if @committee.votes.in_progress.empty? %>
        <p>There are no in progress votes.</p>
      <% else %>
        <table style="width: 100%">
          <tr>
            <th>Title</th>
            <th style="width: 140px" colspan="2">Actions</th>
          </tr>
          <% @committee.votes.in_progress.each do |vote| %>
            <tr>
              <td>
                <%= vote.title %><br />
                &nbsp;&nbsp;&nbsp;<b>Start At:</b> <%= vote.start_at.to_s(:long_with_time) %><br />
                &nbsp;&nbsp;&nbsp;<b>Finish At:</b> <%= vote.finish_at.to_s(:long_with_time) %>
              </td>
              <td>
                <%= link_button_to "Edit&nbsp;Vote".html_safe, edit_vote_path(vote), :size => 'eighty', :class => 'btn blue-btn' %>
              </td>
              <td >
                <%= form_for  vote, :url => {:action => 'cancel', :controller => :votes, :id => vote.id} do |f| %>
                  <%= f.submit "Cancel", :size => 'hundred', :class => 'btn blue-btn' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      <% end %>


      <h2>Previous Votes</h2>

      <% if @committee.votes.finished.empty? %>
        <p>There are no finished votes.</p>
      <% else %>
        <table style="width: 100%">
          <tr>
            <th>Title</th>
            <th style="width: 100px">Outcome</th>
            <th style="width: 140px">Actions</th>
          </tr>
          <% @committee.votes.finished.each do |vote| %>
            <tr>
              <td><%= vote.title %></td>
              <td class="<%= vote.outcome %>"><%= vote.outcome.titleize if vote.outcome %></td>
              <td colspan="3">
                <%= link_button_to "Edit&nbsp;Vote".html_safe, edit_previous_vote_path(vote), :size => 'eighty', :class => 'btn blue-btn' %>
              </td>
            </tr>
          <% end %>
        </table>
      <% end %>
    </div>
</div>

<% else %>
  You are not this committee's chair, you are not allowed to access this information.
<% end %>